SIMPLIFY_HTML = True

TAGS_TO_UNWRAP = [
    "noscript",
]

TAGS_TO_STRIP = [
    "script",
    "link",
    "style",
    "source",
]

ATTRIBUTES_TO_STRIP = ["style", "onclick", "class", "bgcolor", "text", "link", "vlink"]

CAN_RENDER_INLINE_IMAGES = False
RESIZE_IMAGES = True
MAX_IMAGE_WIDTH = 512
MAX_IMAGE_HEIGHT = 342
CONVERT_IMAGES = True
CONVERT_IMAGES_TO_FILETYPE = "gif"
DITHERING_ALGORITHM = "FLOYDSTEINBERG"

CONVERT_CHARACTERS = True

CONVERSION_TABLE = {
    "¢": b"cent",
    "&cent;": b"cent",
    "€": b"EUR",
    "&euro;": b"EUR",
    "&yen;": b"YEN",
    "&pound;": b"GBP",
    "«": b"'",
    "&laquo;": b"'",
    "»": b"'",
    "&raquo;": b"'",
    "‘": b"'",
    "&lsquo;": b"'",
    "’": b"'",
    "&rsquo;": b"'",
    "“": b"''",
    "&ldquo;": b"''",
    "”": b"''",
    "&rdquo;": b"''",
    "–": b"-",
    "&ndash;": b"-",
    "—": b"--",
    "&mdash;": b"--",
    "―": b"-",
    "&horbar;": b"-",
    "·": b"-",
    "&middot;": b"-",
    "‚": b",",
    "&sbquo;": b",",
    "„": b",,",
    "&bdquo;": b",,",
    "†": b"*",
    "&dagger;": b"*",
    "‡": b"**",
    "&Dagger;": b"**",
    "•": b"-",
    "&bull;": b"*",
    "…": b"...",
    "&hellip;": b"...",
    "\u00a0": b" ",
    "&nbsp;": b" ",
    "±": b"+/-",
    "&plusmn;": b"+/-",
    "≈": b"~",
    "&asymp;": b"~",
    "≠": b"!=",
    "&ne;": b"!=",
    "&times;": b"x",
    "⁄": b"/",
    "°": b"*",
    "&deg;": b"*",
    "′": b"'",
    "&prime;": b"'",
    "″": b"''",
    "&Prime;": b"''",
    "™": b"(tm)",
    "&trade;": b"(TM)",
    "&reg;": b"(R)",
    "®": b"(R)",
    "&copy;": b"(c)",
    "©": b"(c)",
    "é": b"e",
    "ø": b"o",
    "Å": b"A",
    "â": b"a",
    "Æ": b"AE",
    "æ": b"ae",
    "á": b"a",
    "ō": b"o",
    "ó": b"o",
    "ū": b"u",
    "⟨": b"<",
    "⟩": b">",
    "←": b"<",
    "›": b">",
    "‹": b"<",
    "&larr;": b"<",
    "→": b">",
    "&rarr;": b">",
    "↑": b"^",
    "&uarr;": b"^",
    "↓": b"v",
    "&darr;": b"v",
    "↖": b"\\",
    "&nwarr;": b"\\",
    "↗": b"/",
    "&nearr;": b"/",
    "↘": b"\\",
    "&searr;": b"\\",
    "↙": b"/",
    "&swarr;": b"/",
    "─": b"-",
    "&boxh;": b"-",
    "│": b"|",
    "&boxv;": b"|",
    "┌": b"+",
    "&boxdr;": b"+",
    "┐": b"+",
    "&boxdl;": b"+",
    "└": b"+",
    "&boxur;": b"+",
    "┘": b"+",
    "&boxul;": b"+",
    "├": b"+",
    "&boxvr;": b"+",
    "┤": b"+",
    "&boxvl;": b"+",
    "┬": b"+",
    "&boxhd;": b"+",
    "┴": b"+",
    "&boxhu;": b"+",
    "┼": b"+",
    "&boxvh;": b"+",
    "█": b"#",
    "&block;": b"#",
    "▌": b"|",
    "&lhblk;": b"|",
    "▐": b"|",
    "&rhblk;": b"|",
    "▀": b"-",
    "&uhblk;": b"-",
    "▄": b"_",
    "&lhblk;": b"_",
    "▾": b"v",
    "&dtrif;": b"v",
    "&#x25BE;": b"v",
    "&#9662;": b"v",
    "♫": b"",
    "&spades;": b"",
    "\u200b": b"",
    "&ZeroWidthSpace;": b"",
    "\u200c": b"",
    "\u200d": b"",
    "\ufeff": b"",
}
